spring.application.name=inomawa

spring.datasource.url=jdbc:postgresql://localhost:5432/inomawa
spring.datasource.username=postgres
spring.datasource.password=itu16

# Affiche les requêtes SQL générées par Hibernate
spring.jpa.show-sql=true

# Formate les requêtes SQL pour une meilleure lisibilité (facultatif)
spring.jpa.properties.hibernate.format_sql=true