spring.application.name=inomawa

spring.datasource.url=jdbc:postgresql://localhost:5432/inomawa
spring.datasource.username=postgres
spring.datasource.password=itu16

# Affiche les requ�tes SQL g�n�r�es par Hibernate
spring.jpa.show-sql=true

# Formate les requ�tes SQL pour une meilleure lisibilit� (facultatif)
spring.jpa.properties.hibernate.format_sql=true